/**
 *  FAQ Json content
 */
export default [
   {
        "question": "Pourquoi les mentions légales sont-elles obligatoires ?",
        "answer": "<p>Les mentions légales sont obligatoires pour tout site web car elles permettent à tout internaute d'identifier clairement le responsable du site (ainsi que son hébergeur) sur lequel il navigue. L'internaute ou les autorités judiciaires peuvent ainsi contacter l'éditeur en cas de diffusion de contenus contrevenant à la loi.</p><p><strong>Besoin d'aide pour accélérer votre transition numérique ? <a href='mailto:bonjour@silexia.fr'>Contactez-nous !</a></strong></p>",
        "short_answer": "Les mentions légales sont obligatoires pour tout site web car elles permettent à tout internaute d'identifier clairement le responsable du site (ainsi que son hébergeur) sur lequel il navigue. L'internaute ou les autorités judiciaires peuvent ainsi contacter l'éditeur en cas de diffusion de contenus contrevenant à la loi."
    },
    {
        "question": "À qui s'adresse ce générateur de mentions légales profesionnelles ?",
        "answer": "<p>Notre générateur de mentions légales s'adresse aux entreprises commerciales, dans l'artisanat, aux autoentrepreneurs, aux professionnels réglementés et à ceux soumis à une autorisation préalable à la mise en ligne de leur site par un organisme professionel.</p><p>Notre générateur n'est pas fait pour les mentions légales d'un site d'information.</p><p><strong>Besoin d'aide pour accélérer votre transition numérique ? <a href='mailto:bonjour@silexia.fr'>Contactez-nous !</a></strong></p>",
        "short_answer": "Notre générateur de mentions légales s'adresse aux entreprises commerciales, dans l'artisanat, aux autoentrepreneurs, aux professionnels réglementés et à ceux soumis à une autorisation préalable à la mise en ligne de leur site par un organisme professionel."
    },
    {
        "question": "Quelles sont les informations à faire apparaître dans mes mentions légales ?",
        "answer": "<p>Les informations à présenter dans les mentions légales d'un site web dépendent du statut de l'entreprise ou du professionnel. Notre générateur porte une attention particulière à comprendre votre statut pour adapter vos mentions légales à votre situation.</p><p>Notre générateur n'est pas fait pour les mentions légales d'un site d'information.</p><p><strong>Besoin d'aide pour accélérer votre transition numérique ? <a href='mailto:bonjour@silexia.fr'>Contactez-nous !</a></strong></p>",
        "short_answer": "Les informations à présenter dans les mentions légales d'un site web dépendent du statut de l'entreprise ou du professionnel. Notre générateur porte une attention particulière à comprendre votre statut pour adapter vos mentions légales à votre situation." 
    },
    {
        "question": "Quels autres documents légaux sont obligatoires pour mon site ?",
        "answer": "<p><strong>Dans le cas d'un site vitrine, seules les mentions légales sont absolument obligatoires.</strong></p><p>Toutefois, <strong>il est fortement recommandé de mettre en ligne votre politique de confidentialité</strong>. En effet, il s'agit avec ce document de présenter aux internautes naviguant sur votre site tout ce que vous faites avec leurs données à caractère personnel. Dans tous les cas, lorsque vous collectez des données à caractère personnel, vous devez&nbsp;informer vos utilisateurs de l'usage qui sera fait de leurs données et collecter leur consentement à cet usage (qui ne saurait être détourné). Il s'agit ici de votre conformité au Règlement Général sur la Protection des Données (tout contrevenant s'expose à une amende équivalente à 4 % du chiffre d'affaires mondial de votre entreprise).</p><p><strong>Si votre site est un site de e-commerce, vous êtes dans l'obligation d'afficher des conditions générales de vente</strong>, document qui a valeur contractuelle. Ces CGV décrivent toutes les modalités de votre processus de vente, les droits de vos consommateurs ainsi que les obligations liées à la livraison de vos services et produits.</p><p>Enfin, <strong>il est recommandé de rédiger des conditions générales d'utilisation</strong> dans le cas d'un site disposant d'un espace membre fermé ou pour un site riche en fonctionnalités et services tiers. Ce document a valeur contractuel vous permet de définir vos responsabilités et celles de vos utilisateurs. Ces CGU décrivent également le fonctionnement et les modalités d'accès aux services que vous proposez sur votre site.</p><p><strong>Nos générateurs de politique de confidentialité, CGV et CGU sont en cours de développement. Dites-nous si ce type de services vous intéresse. </strong><a href='mailto:bonjour@silexia.fr'><strong>Contactez-nous !</strong></a></p>",
        "short_answer": "Dans le cas d'un site vitrine, seules les mentions légales sont absolument obligatoires. Toutefois, il est fortement recommandé de mettre en ligne votre politique de confidentialité. Si votre site est un site de e-commerce, vous êtes dans l'obligation d'afficher des conditions générales de vente, document qui a valeur contractuelle. Enfin, il est recommandé de rédiger des conditions générales d'utilisation dans le cas d'un site disposant d'un espace membre fermé ou pour un site riche en fonctionnalités et services tiers."
    },
    {
        "question": "Quel risque pour mon entreprise si elle ne se conforme pas aux exigences propres aux mentions légales ?",
        "answer": "<p>En cas de manquement à l'obligation de présenter ses mentions légales, un professionnel ou une entreprise (ainsi que son dirigeant) s'expose à 375 000 euros, 5 ans d'emprisonnement et l'interdiction d'exercer plusieurs activités professionnelles. Pour un particulier, le contrevenant s'expose à 75 000 euros d'amende et 1 an de prison.</p><p><strong>Besoin d'aide pour accélérer votre transition numérique ? <a href='mailto:bonjour@silexia.fr'>Contactez-nous !</a></strong></p>",
        "short_answer": "En cas de manquement à l'obligation de présenter ses mentions légales, un professionnel ou une entreprise (ainsi que son dirigeant) s'expose à 375 000 euros, 5 ans d'emprisonnement et l'interdiction d'exercer plusieurs activités professionnelles. Pour un particulier, le contrevenant s'expose à 75 000 euros d'amende et 1 an de prison."
    },
    {
        "question": "Le service de génération de mentions légales est-il gratuit ?",
        "answer": "<p>Oui ! Notre générateur de mentions légales est totalement gratuit. Nous voulons par cet outil vous aider à mettre en conformité votre site pour éviter toute mauvaise surprise...</p><p><strong>Besoin d'aide pour accélérer votre transition numérique ? <a href='mailto:bonjour@silexia.fr'>Contactez-nous !</a></strong></p>",
        "short_answer": "Oui ! Notre générateur de mentions légales est totalement gratuit. Nous voulons par cet outil vous aider à mettre en conformité votre site pour éviter toute mauvaise surprise..."
    },
]